(ns fluree.db.constants
  (:require [fluree.db.json-ld.iri :as iri :refer [fluree-iri fluree-idx-iri]]))

#?(:clj (set! *warn-on-reflection* true))

;; Version
(def ^:const data_version 4)

;; iri constants
(def ^:const iri-CommitProof (fluree-iri "CommitProof"))
(def ^:const iri-Commit (fluree-iri "Commit"))
(def ^:const iri-commit (fluree-iri "commit"))
(def ^:const iri-DB (fluree-iri "DB"))
(def ^:const iri-data (fluree-iri "data"))
(def ^:const iri-fluree-t (fluree-iri "t"))
(def ^:const iri-address (fluree-iri "address"))
(def ^:const iri-v (fluree-iri "v"))
(def ^:const iri-flakes (fluree-iri "flakes"))
(def ^:const iri-size (fluree-iri "size"))
(def ^:const iri-assert (fluree-iri "assert"))
(def ^:const iri-retract (fluree-iri "retract"))
(def ^:const iri-previous (fluree-iri "previous"))
(def ^:const iri-alias (fluree-iri "alias"))
(def ^:const iri-ledger (fluree-iri "ledger"))
(def ^:const iri-branch (fluree-iri "branch"))
(def ^:const iri-namespaces (fluree-iri "namespaces"))
(def ^:const iri-issuer "https://www.w3.org/2018/credentials#issuer")
(def ^:const iri-cred-subj "https://www.w3.org/2018/credentials#credentialSubject")
(def ^:const iri-index (fluree-iri "index"))
(def ^:const iri-ns (fluree-iri "ns"))
(def ^:const iri-time (fluree-iri "time"))
(def ^:const iri-author (fluree-iri "author"))
(def ^:const iri-txn (fluree-iri "txn"))
(def ^:const iri-annotation (fluree-iri "annotation"))
(def ^:const iri-message (fluree-iri "message"))
(def ^:const iri-tag (fluree-iri "tag"))
(def ^:const iri-updates (fluree-iri "updates"))
(def ^:const iri-allow (fluree-iri "allow"))
(def ^:const iri-equals (fluree-iri "equals"))
(def ^:const iri-contains (fluree-iri "contains"))
(def ^:const iri-$identity (fluree-iri "$identity"))
(def ^:const iri-target-role (fluree-iri "targetRole"))
(def ^:const iri-target-class (fluree-iri "targetClass"))
(def ^:const iri-target-node (fluree-iri "targetNode"))
(def ^:const iri-target-objects-of (fluree-iri "targetObjectsOf"))
(def ^:const iri-property (fluree-iri "property"))
(def ^:const iri-access-policy (fluree-iri "AccessPolicy"))
(def ^:const iri-opts (fluree-iri "opts"))
(def ^:const iri-path (fluree-iri "path"))
(def ^:const iri-action (fluree-iri "action"))
(def ^:const iri-all-nodes (fluree-iri "allNodes"))
(def ^:const iri-view (fluree-iri "view"))
(def ^:const iri-modify (fluree-iri "modify"))
(def ^:const iri-role (fluree-iri "role"))
(def ^:const iri-where (fluree-iri "where"))
(def ^:const iri-values (fluree-iri "values"))
(def ^:const iri-insert (fluree-iri "insert"))
(def ^:const iri-delete (fluree-iri "delete"))
(def ^:const iri-rule (fluree-iri "rule"))
(def ^:const iri-query (fluree-iri "query"))
(def ^:const iri-onClass (fluree-iri "onClass"))
(def ^:const iri-required (fluree-iri "required"))
(def ^:const iri-onProperty (fluree-iri "onProperty"))
(def ^:const iri-onSubject (fluree-iri "onSubject"))
(def ^:const iri-targetSubject (fluree-iri "targetSubject"))
(def ^:const iri-targetProperty (fluree-iri "targetProperty"))
(def ^:const iri-targetObject (fluree-iri "targetObject"))
(def ^:const iri-exMessage (fluree-iri "exMessage"))
(def ^:const iri-policyClass (fluree-iri "policyClass"))
(def ^:const iri-vector (fluree-iri "vector"))
(def ^:const iri-sparseVector (fluree-iri "sparseVector"))
(def ^:const iri-VirtualGraph (fluree-iri "VirtualGraph"))
(def ^:const iri-virtualGraph (fluree-iri "virtualGraph"))

(def ^:const iri-index-BM25 (fluree-idx-iri "BM25"))
(def ^:const iri-index-b (fluree-idx-iri "b"))
(def ^:const iri-index-k1 (fluree-idx-iri "k1"))
(def ^:const iri-index-target (fluree-idx-iri "target"))
(def ^:const iri-index-property (fluree-idx-iri "property"))
(def ^:const iri-index-limit (fluree-idx-iri "limit"))
(def ^:const iri-index-id (fluree-idx-iri "id"))
(def ^:const iri-index-score (fluree-idx-iri "score"))
(def ^:const iri-index-result (fluree-idx-iri "result"))
(def ^:const iri-index-vector (fluree-idx-iri "vector"))
(def ^:const iri-index-sync (fluree-idx-iri "sync"))
(def ^:const iri-index-timeout (fluree-idx-iri "timeout"))

(def ^:const iri-context "@context")
(def ^:const iri-base "@base")
(def ^:const iri-vocab "@vocab")
(def ^:const iri-id "@id")
(def ^:const iri-value "@value")
(def ^:const iri-language "@language")
(def ^:const iri-type "@type")
(def ^:const iri-json "@json")
(def ^:const iri-list "@list")
(def ^:const iri-set "@set")
(def ^:const iri-filter "@filter")
(def ^:const iri-t "@t")
(def ^:const iri-variable "@variable")
(def ^:const iri-anyURI "http://www.w3.org/2001/XMLSchema#anyURI")
(def ^:const iri-rdf-type "http://www.w3.org/1999/02/22-rdf-syntax-ns#type")
(def ^:const iri-rdf-first "http://www.w3.org/1999/02/22-rdf-syntax-ns#first")
(def ^:const iri-rdf-rest "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest")
(def ^:const iri-rdf-nil "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil")
(def ^:const iri-rdf-json "http://www.w3.org/1999/02/22-rdf-syntax-ns#JSON")
(def ^:const iri-class "http://www.w3.org/2000/01/rdf-schema#Class")
(def ^:const iri-lang-string "http://www.w3.org/1999/02/22-rdf-syntax-ns#langString")

;; xsd
(def ^:const iri-xsd-boolean "http://www.w3.org/2001/XMLSchema#boolean")
(def ^:const iri-xsd-date "http://www.w3.org/2001/XMLSchema#date")
(def ^:const iri-xsd-dateTime "http://www.w3.org/2001/XMLSchema#dateTime")
(def ^:const iri-string "http://www.w3.org/2001/XMLSchema#string")
;; xsd number types
(def ^:const iri-xsd-decimal "http://www.w3.org/2001/XMLSchema#decimal")
(def ^:const iri-xsd-double "http://www.w3.org/2001/XMLSchema#double")
(def ^:const iri-xsd-integer "http://www.w3.org/2001/XMLSchema#integer")
(def ^:const iri-long "http://www.w3.org/2001/XMLSchema#long")
(def ^:const iri-xsd-int "http://www.w3.org/2001/XMLSchema#int")
(def ^:const iri-xsd-short "http://www.w3.org/2001/XMLSchema#short")
(def ^:const iri-xsd-float "http://www.w3.org/2001/XMLSchema#float")
(def ^:const iri-xsd-unsignedLong "http://www.w3.org/2001/XMLSchema#unsignedLong")
(def ^:const iri-xsd-unsignedInt "http://www.w3.org/2001/XMLSchema#unsignedInt")
(def ^:const iri-xsd-unsignedShort "http://www.w3.org/2001/XMLSchema#unsignedShort")
(def ^:const iri-xsd-positiveInteger "http://www.w3.org/2001/XMLSchema#positiveInteger")
(def ^:const iri-xsd-nonPositiveInteger "http://www.w3.org/2001/XMLSchema#nonPositiveInteger")
(def ^:const iri-xsd-negativeInteger "http://www.w3.org/2001/XMLSchema#negativeInteger")
(def ^:const iri-xsd-nonNegativeInteger "http://www.w3.org/2001/XMLSchema#nonNegativeInteger")
;; xsd date and specialized strings
(def ^:const iri-xsd-duration "http://www.w3.org/2001/XMLSchema#duration")
(def ^:const iri-xsd-gDay "http://www.w3.org/2001/XMLSchema#gDay")
(def ^:const iri-xsd-gMonth "http://www.w3.org/2001/XMLSchema#gMonth")
(def ^:const iri-xsd-gMonthDay "http://www.w3.org/2001/XMLSchema#gMonthDay")
(def ^:const iri-xsd-gYear "http://www.w3.org/2001/XMLSchema#gYear")
(def ^:const iri-xsd-gYearMonth "http://www.w3.org/2001/XMLSchema#gYearMonth")
(def ^:const iri-xsd-time "http://www.w3.org/2001/XMLSchema#time")
(def ^:const iri-xsd-normalizedString "http://www.w3.org/2001/XMLSchema#normalizedString")
(def ^:const iri-xsd-token "http://www.w3.org/2001/XMLSchema#token")
(def ^:const iri-xsd-language "http://www.w3.org/2001/XMLSchema#language")
;; xsd binary types
(def ^:const iri-xsd-byte "http://www.w3.org/2001/XMLSchema#byte")
(def ^:const iri-xsd-unsignedByte "http://www.w3.org/2001/XMLSchema#unsignedByte")
(def ^:const iri-xsd-hexBinary "http://www.w3.org/2001/XMLSchema#hexBinary")
(def ^:const iri-xsd-base64Binary "http://www.w3.org/2001/XMLSchema#base64Binary")

;; rdfs
(def ^:const iri-rdfs:Class "http://www.w3.org/2000/01/rdf-schema#Class")
(def ^:const iri-rdfs:subClassOf "http://www.w3.org/2000/01/rdf-schema#subClassOf")
(def ^:const iri-rdfs:subPropertyOf "http://www.w3.org/2000/01/rdf-schema#subPropertyOf")
(def ^:const iri-rdfs:domain "http://www.w3.org/2000/01/rdf-schema#domain")
(def ^:const iri-rdfs:range "http://www.w3.org/2000/01/rdf-schema#range")

;; OWL
(def ^:const iri-owl:Thing "http://www.w3.org/2002/07/owl#Thing")
(def ^:const iri-owl:Class "http://www.w3.org/2002/07/owl#Class")
(def ^:const iri-owl:ObjectProperty "http://www.w3.org/2002/07/owl#ObjectProperty")
(def ^:const iri-owl:FunctionalProperty "http://www.w3.org/2002/07/owl#FunctionalProperty")
(def ^:const iri-owl:InverseFunctionalProperty "http://www.w3.org/2002/07/owl#InverseFunctionalProperty")
(def ^:const iri-owl:SymetricProperty "http://www.w3.org/2002/07/owl#SymetricProperty")
(def ^:const iri-owl:TransitiveProperty "http://www.w3.org/2002/07/owl#TransitiveProperty")

(def ^:const iri-owl:sameAs "http://www.w3.org/2002/07/owl#sameAs")

;; property expressions
(def ^:const iri-owl:propertyChainAxiom "http://www.w3.org/2002/07/owl#propertyChainAxiom")
(def ^:const iri-owl:inverseOf "http://www.w3.org/2002/07/owl#inverseOf")
(def ^:const iri-owl:hasKey "http://www.w3.org/2002/07/owl#hasKey")

;; class expressions
(def ^:const iri-owl:equivalentClass "http://www.w3.org/2002/07/owl#equivalentClass")
(def ^:const iri-owl:intersectionOf "http://www.w3.org/2002/07/owl#intersectionOf")
(def ^:const iri-owl:unionOf "http://www.w3.org/2002/07/owl#unionOf")
(def ^:const iri-owl:Restriction "http://www.w3.org/2002/07/owl#Restriction")
(def ^:const iri-owl:onProperty "http://www.w3.org/2002/07/owl#onProperty")
(def ^:const iri-owl:onClass "http://www.w3.org/2002/07/owl#onClass")
(def ^:const iri-owl:oneOf "http://www.w3.org/2002/07/owl#oneOf")
(def ^:const iri-owl:hasValue "http://www.w3.org/2002/07/owl#hasValue")
(def ^:const iri-owl:someValuesFrom "http://www.w3.org/2002/07/owl#someValuesFrom")
(def ^:const iri-owl:allValuesFrom "http://www.w3.org/2002/07/owl#allValuesFrom")
(def ^:const iri-owl:maxCardinality "http://www.w3.org/2002/07/owl#maxCardinality")
(def ^:const iri-owl:maxQualifiedCardinality "http://www.w3.org/2002/07/owl#maxQualifiedCardinality")
(def ^:const iri-owl:qualifiedCardinality "http://www.w3.org/2002/07/owl#qualifiedCardinality")

;; SHACL validation report iris
(def ^:const iri_ValidationReport "http://www.w3.org/ns/shacl#ValidationReport")
(def ^:const iri_conforms "http://www.w3.org/ns/shacl#conforms")
(def ^:const iri_shapesGraphWellFormed "http://www.w3.org/ns/shacl#shapesGraphWellFormed")
(def ^:const iri_result "http://www.w3.org/ns/shacl#result")
(def ^:const iri_ValidationResult "http://www.w3.org/ns/shacl#ValidationResult")
(def ^:const iri_focusNode "http://www.w3.org/ns/shacl#focusNode")
(def ^:const iri_resultPath "http://www.w3.org/ns/shacl#resultPath")
(def ^:const iri_value "http://www.w3.org/ns/shacl#value")
(def ^:const iri_sourceShape "http://www.w3.org/ns/shacl#sourceShape")
(def ^:const iri_constraintComponent "http://www.w3.org/ns/shacl#constraintComponent")
(def ^:const iri_details "http://www.w3.org/ns/shacl#details")
(def ^:const iri_resultMessage "http://www.w3.org/ns/shacl#resultMessage")
(def ^:const iri_resultSeverity "http://www.w3.org/ns/shacl#resultSeverity")
(def ^:const iri_Violation "http://www.w3.org/ns/shacl#Violation")
(def ^:const iri_expectation (fluree-iri "expectation"))

;; predicate id constants

(def ^:const $_previous (iri/iri->sid iri-previous))
(def ^:const $_v (iri/iri->sid iri-v))
(def ^:const $_address (iri/iri->sid iri-address))
(def ^:const $_commit:message (iri/iri->sid iri-message))
(def ^:const $_commit:time (iri/iri->sid iri-time))
(def ^:const $_commit:signer (iri/iri->sid iri-issuer))
(def ^:const $_commit:author (iri/iri->sid iri-author))
(def ^:const $_commit:txn (iri/iri->sid iri-txn))
(def ^:const $_commit:annotation (iri/iri->sid iri-annotation))
(def ^:const $_ledger:alias (iri/iri->sid iri-alias))
(def ^:const $_ledger:branch (iri/iri->sid iri-branch))

(def ^:const $_commit:data (iri/iri->sid iri-data))
(def ^:const $_commitdata:flakes (iri/iri->sid iri-flakes))
(def ^:const $_commitdata:size (iri/iri->sid iri-size))
(def ^:const $_commitdata:t (iri/iri->sid iri-fluree-t))

(def ^:const $id (iri/iri->sid iri-id))

(def ^:const $rdf:type iri/type-sid)
(def ^:const $rdf:Property (iri/iri->sid "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"))
(def ^:const $rdf:langString (iri/iri->sid "http://www.w3.org/1999/02/22-rdf-syntax-ns#langString"))

(def ^:const $rdfs:subClassOf (iri/iri->sid iri-rdfs:subClassOf))
(def ^:const $rdfs:subPropertyOf (iri/iri->sid iri-rdfs:subPropertyOf))
(def ^:const $rdfs:Class (iri/iri->sid iri-rdfs:Class))

;; shacl
(def ^:const sh_NodeShape (iri/iri->sid "http://www.w3.org/ns/shacl#NodeShape"))
(def ^:const sh_deactivated (iri/iri->sid "http://www.w3.org/ns/shacl#deactivated"))
(def ^:const sh_message (iri/iri->sid "http://www.w3.org/ns/shacl#message"))
(def ^:const sh_severity (iri/iri->sid "http://www.w3.org/ns/shacl#severity"))

(def ^:const sh_PropertyShape (iri/iri->sid "http://www.w3.org/ns/shacl#PropertyShape"))
(def ^:const sh_path (iri/iri->sid "http://www.w3.org/ns/shacl#path"))

(def ^:const sh_alternativePath (iri/iri->sid "http://www.w3.org/ns/shacl#alternativePath"))
(def ^:const sh_zeroOrMorePath (iri/iri->sid "http://www.w3.org/ns/shacl#zeroOrMorePath"))
(def ^:const sh_oneOrMorePath (iri/iri->sid "http://www.w3.org/ns/shacl#oneOrMorePath"))
(def ^:const sh_zeroOrOnePath (iri/iri->sid "http://www.w3.org/ns/shacl#zeroOrOnePath"))
(def ^:const sh_inversePath (iri/iri->sid "http://www.w3.org/ns/shacl#inversePath"))

;; targets
(def ^:const sh_targetClass (iri/iri->sid "http://www.w3.org/ns/shacl#targetClass"))
(def ^:const sh_targetNode (iri/iri->sid "http://www.w3.org/ns/shacl#targetNode"))
(def ^:const sh_targetObjectsOf (iri/iri->sid "http://www.w3.org/ns/shacl#targetObjectsOf"))
(def ^:const sh_targetSubjectsOf (iri/iri->sid "http://www.w3.org/ns/shacl#targetSubjectsOf"))

;; constraints:
;; value type
(def ^:const sh_class (iri/iri->sid "http://www.w3.org/ns/shacl#class"))
(def ^:const sh_datatype (iri/iri->sid "http://www.w3.org/ns/shacl#datatype"))
(def ^:const sh_nodeKind (iri/iri->sid "http://www.w3.org/ns/shacl#nodeKind"))

(def ^:const sh_IRI (iri/iri->sid "http://www.w3.org/ns/shacl#IRI"))
(def ^:const sh_IRIOrLiteral (iri/iri->sid "http://www.w3.org/ns/shacl#IRIOrLiteral"))
(def ^:const sh_BlankNodeOrIRI (iri/iri->sid "http://www.w3.org/ns/shacl#BlankNodeOrIRI"))
(def ^:const sh_BlankNode (iri/iri->sid "http://www.w3.org/ns/shacl#BlankNode"))
(def ^:const sh_BlankNodeOrLiteral (iri/iri->sid "http://www.w3.org/ns/shacl#BlankNodeOrLiteral"))
(def ^:const sh_Literal (iri/iri->sid "http://www.w3.org/ns/shacl#Literal"))

;; cardinality
(def ^:const sh_minCount (iri/iri->sid "http://www.w3.org/ns/shacl#minCount"))
(def ^:const sh_maxCount (iri/iri->sid "http://www.w3.org/ns/shacl#maxCount"))

;; value range
(def ^:const sh_minExclusive (iri/iri->sid "http://www.w3.org/ns/shacl#minExclusive"))
(def ^:const sh_minInclusive (iri/iri->sid "http://www.w3.org/ns/shacl#minInclusive"))
(def ^:const sh_maxExclusive (iri/iri->sid "http://www.w3.org/ns/shacl#maxExclusive"))
(def ^:const sh_maxInclusive (iri/iri->sid "http://www.w3.org/ns/shacl#maxInclusive"))

;; string-based
(def ^:const sh_minLength (iri/iri->sid "http://www.w3.org/ns/shacl#minLength"))
(def ^:const sh_maxLength (iri/iri->sid "http://www.w3.org/ns/shacl#maxLength"))
(def ^:const sh_pattern (iri/iri->sid "http://www.w3.org/ns/shacl#pattern"))
(def ^:const sh_flags (iri/iri->sid "http://www.w3.org/ns/shacl#flags"))
(def ^:const sh_languageIn (iri/iri->sid "http://www.w3.org/ns/shacl#languageIn"))
(def ^:const sh_uniqueLang (iri/iri->sid "http://www.w3.org/ns/shacl#uniqueLang"))

;; property pair
(def ^:const sh_equals (iri/iri->sid "http://www.w3.org/ns/shacl#equals"))
(def ^:const sh_disjoint (iri/iri->sid "http://www.w3.org/ns/shacl#disjoint"))
(def ^:const sh_lessThan (iri/iri->sid "http://www.w3.org/ns/shacl#lessThan"))
(def ^:const sh_lessThanOrEquals (iri/iri->sid "http://www.w3.org/ns/shacl#lessThanOrEquals"))

;; logical constraints
(def ^:const sh_not (iri/iri->sid "http://www.w3.org/ns/shacl#not"))
(def ^:const sh_and (iri/iri->sid "http://www.w3.org/ns/shacl#and"))
(def ^:const sh_or (iri/iri->sid "http://www.w3.org/ns/shacl#or"))
(def ^:const sh_xone (iri/iri->sid "http://www.w3.org/ns/shacl#xone"))

;; shape-based
(def ^:const sh_property (iri/iri->sid "http://www.w3.org/ns/shacl#property"))
(def ^:const sh_node (iri/iri->sid "http://www.w3.org/ns/shacl#node"))
(def ^:const sh_qualifiedValueShape (iri/iri->sid "http://www.w3.org/ns/shacl#qualifiedValueShape"))
(def ^:const sh_qualifiedMinCount (iri/iri->sid "http://www.w3.org/ns/shacl#qualifiedMinCount"))
(def ^:const sh_qualifiedMaxCount (iri/iri->sid "http://www.w3.org/ns/shacl#qualifiedMaxCount"))
(def ^:const sh_qualifiedValueShapesDisjoint (iri/iri->sid "http://www.w3.org/ns/shacl#qualifiedValueShapesDisjoint"))

;; other
(def ^:const sh_closed (iri/iri->sid "http://www.w3.org/ns/shacl#closed"))
(def ^:const sh_ignoredProperties (iri/iri->sid "http://www.w3.org/ns/shacl#ignoredProperties"))
(def ^:const sh_in (iri/iri->sid "http://www.w3.org/ns/shacl#in"))
(def ^:const sh_hasValue (iri/iri->sid "http://www.w3.org/ns/shacl#hasValue"))

;; owl
(def ^:const $owl:Class (iri/iri->sid "http://www.w3.org/2002/07/owl#Class"))
(def ^:const $owl:ObjectProperty (iri/iri->sid "http://www.w3.org/2002/07/owl#ObjectProperty"))
(def ^:const $owl:DatatypeProperty (iri/iri->sid "http://www.w3.org/2002/07/owl#DatatypeProperty"))
(def ^:const $owl:equivalentProperty (iri/iri->sid "http://www.w3.org/2002/07/owl#equivalentProperty"))

;; == data types ==
;; major types (a) ref, (b) string, (c) number, (d) boolean
;; xsd common types
(def ^:const $xsd:anyURI (iri/iri->sid iri-anyURI))
(def ^:const $xsd:string (iri/iri->sid iri-string))
(def ^:const $xsd:boolean (iri/iri->sid iri-xsd-boolean))
(def ^:const $xsd:date (iri/iri->sid iri-xsd-date))
(def ^:const $xsd:dateTime (iri/iri->sid iri-xsd-dateTime))
;; xsd number types
(def ^:const $xsd:decimal (iri/iri->sid iri-xsd-decimal))
(def ^:const $xsd:double (iri/iri->sid iri-xsd-double))
(def ^:const $xsd:integer (iri/iri->sid iri-xsd-integer))
(def ^:const $xsd:long (iri/iri->sid iri-long))
(def ^:const $xsd:int (iri/iri->sid iri-xsd-int))
(def ^:const $xsd:short (iri/iri->sid iri-xsd-short))
(def ^:const $xsd:float (iri/iri->sid iri-xsd-float))
(def ^:const $xsd:unsignedLong (iri/iri->sid iri-xsd-unsignedLong))
(def ^:const $xsd:unsignedInt (iri/iri->sid iri-xsd-unsignedInt))
(def ^:const $xsd:unsignedShort (iri/iri->sid iri-xsd-unsignedShort))
(def ^:const $xsd:positiveInteger (iri/iri->sid iri-xsd-positiveInteger))
(def ^:const $xsd:nonPositiveInteger (iri/iri->sid iri-xsd-nonPositiveInteger))
(def ^:const $xsd:negativeInteger (iri/iri->sid iri-xsd-negativeInteger))
(def ^:const $xsd:nonNegativeInteger (iri/iri->sid iri-xsd-nonNegativeInteger))
;; xsd date and specialized strings
(def ^:const $xsd:duration (iri/iri->sid iri-xsd-duration))
(def ^:const $xsd:gDay (iri/iri->sid iri-xsd-gDay))
(def ^:const $xsd:gMonth (iri/iri->sid iri-xsd-gMonth))
(def ^:const $xsd:gMonthDay (iri/iri->sid iri-xsd-gMonthDay))
(def ^:const $xsd:gYear (iri/iri->sid iri-xsd-gYear))
(def ^:const $xsd:gYearMonth (iri/iri->sid iri-xsd-gYearMonth))
(def ^:const $xsd:time (iri/iri->sid iri-xsd-time))
(def ^:const $xsd:normalizedString (iri/iri->sid iri-xsd-normalizedString))
(def ^:const $xsd:token (iri/iri->sid iri-xsd-token))
(def ^:const $xsd:language (iri/iri->sid iri-xsd-language))
;; xsd binary types
(def ^:const $xsd:byte (iri/iri->sid iri-xsd-byte)) ; store as number
(def ^:const $xsd:unsignedByte (iri/iri->sid iri-xsd-unsignedByte)) ; store as number
(def ^:const $xsd:hexBinary (iri/iri->sid iri-xsd-hexBinary))
(def ^:const $xsd:base64Binary (iri/iri->sid iri-xsd-base64Binary))
(def ^:const $rdf:json (iri/iri->sid iri-rdf-json))
(def ^:const $fluree:vector (iri/iri->sid iri-vector)) ;; dense vector/embedding
(def ^:const $fluree:VirtualGraph (iri/iri->sid iri-VirtualGraph))
(def ^:const $fluree:virtualGraph-name (iri/iri->sid iri-virtualGraph))
(def ^:const $fluree:query (iri/iri->sid iri-query))
(def ^:const $fluree:index-BM25 (iri/iri->sid iri-index-BM25))
(def ^:const $fluree:index-b (iri/iri->sid iri-index-b))
(def ^:const $fluree:index-k1 (iri/iri->sid iri-index-k1))
;; NOTE: Add multibyte type?
;; NOTE: Add geo types? string-encoded GeoJSON?
