# Native core; the public API is in the `fluree` package.

from os import PathLike
from typing import Any

__version__: str

Term = tuple[Any, ...]
TimeSpec = tuple[str, int | str]
# {"max_fuel": float | None, "timeout": float | None, "stats": bool}
Controls = dict[str, Any]

class Connection:
    @staticmethod
    def memory() -> Connection: ...
    @staticmethod
    def file(path: PathLike[str], *, indexing: bool = True) -> Connection: ...
    @staticmethod
    def from_config(config: dict[str, Any]) -> Connection: ...
    def create(self, ledger: str, source: PathLike[str] | None = None) -> str: ...
    def exists(self, ledger: str) -> bool: ...
    def ledger(self, ledger: str) -> str: ...
    def ledgers(self) -> list[str]: ...
    def drop(self, ledger: str) -> None: ...
    def close(self) -> None: ...
    def sync(
        self,
        ledger: str,
        kind: str,
        payload: Any,
        graph: str | None = None,
        allow_empty: bool = False,
        dry_run: bool = False,
        policy: dict[str, Any] | None = None,
        message: str | None = None,
    ) -> dict[str, Any]: ...
    def begin(self, ledger: str, policy: dict[str, Any] | None = None) -> Transaction: ...
    def cypher_query(
        self,
        ledger: str,
        cypher: str,
        params: dict[str, Any] | None = None,
        at: tuple[str, Any] | None = None,
        policy: dict[str, Any] | None = None,
        controls: Controls | None = None,
    ) -> tuple[list[str], list[tuple[Any, ...]]]: ...
    def explain_cypher(
        self,
        ledger: str,
        cypher: str,
        params: dict[str, Any] | None = None,
        at: tuple[str, Any] | None = None,
        policy: dict[str, Any] | None = None,
    ) -> dict[str, Any]: ...
    def validate(self, ledger: str, options: dict[str, Any]) -> dict[str, Any]: ...
    def index_status(self, ledger: str) -> dict[str, Any]: ...
    def index(self, ledger: str, timeout: float | None = None) -> int: ...
    def reindex(self, ledger: str) -> int: ...
    def verify(self, ledger: str, max_commits: int | None = None) -> dict[str, Any]: ...
    def sweep(self, ledger: str, dry_run: bool) -> dict[str, Any]: ...
    def transact(
        self,
        ledger: str,
        op: str,
        kind: str,
        payload: Any,
        policy: dict[str, Any] | None = None,
        message: str | None = None,
        params: dict[str, Any] | None = None,
    ) -> dict[str, Any]: ...
    def query_sparql(
        self,
        ledger: str,
        sparql: str,
        at: TimeSpec | None = None,
        policy: dict[str, Any] | None = None,
        controls: Controls | None = None,
        params: dict[str, Any] | None = None,
    ) -> Any: ...
    def query_jsonld(
        self,
        ledger: str,
        query: Any,
        at: TimeSpec | None = None,
        policy: dict[str, Any] | None = None,
        controls: Controls | None = None,
    ) -> Any: ...
    def explain(
        self,
        ledger: str,
        query: Any,
        at: TimeSpec | None = None,
        policy: dict[str, Any] | None = None,
        params: dict[str, Any] | None = None,
    ) -> dict[str, Any]: ...
    def stream(
        self,
        ledger: str,
        query: Any,
        at: TimeSpec | None = None,
        policy: dict[str, Any] | None = None,
        controls: Controls | None = None,
        params: dict[str, Any] | None = None,
    ) -> RowStream: ...
    def query_sparql_from(
        self,
        sparql: str,
        policy: dict[str, Any] | None = None,
        controls: Controls | None = None,
        params: dict[str, Any] | None = None,
    ) -> Any: ...
    def query_jsonld_from(self, query: Any, controls: Controls | None = None) -> Any: ...
    def snapshot(
        self, ledger: str, at: TimeSpec | None = None, policy: dict[str, Any] | None = None
    ) -> Snapshot: ...
    def log(self, ledger: str, limit: int | None = None) -> tuple[list[dict[str, Any]], int]: ...
    def commit_detail(
        self, ledger: str, commit: int | str, policy: dict[str, Any] | None = None
    ) -> dict[str, Any]: ...
    def export(
        self,
        ledger: str,
        format: str,
        path: PathLike[str] | None = None,
        graph: str | None = None,
        all_graphs: bool = False,
        context: Any = None,
        at: TimeSpec | None = None,
    ) -> tuple[str | None, int]: ...
    def archive(self, ledger: str, path: PathLike[str], include_indexes: bool = True) -> None: ...
    def restore(self, path: PathLike[str], ledger: str) -> str: ...
    def context(self, ledger: str) -> dict[str, Any] | None: ...
    def set_context(self, ledger: str, context: dict[str, Any]) -> None: ...
    def info(self, ledger: str) -> dict[str, Any]: ...
    def drop_graph(self, ledger: str, graph: str) -> dict[str, Any]: ...
    def map_iceberg(self, common: dict[str, Any], spec: dict[str, Any]) -> dict[str, Any]: ...
    def map_delta(self, common: dict[str, Any], spec: dict[str, Any]) -> dict[str, Any]: ...
    def map_sql(self, common: dict[str, Any], spec: dict[str, Any]) -> dict[str, Any]: ...
    def graph_sources(self) -> list[dict[str, Any]]: ...
    def drop_graph_source(self, name: str, branch: str) -> None: ...
    def materialize(self, source: str, into: str, full: bool = False) -> dict[str, Any]: ...
    def query_graph(
        self,
        graph: str,
        query: Any,
        controls: Controls | None = None,
        params: dict[str, Any] | None = None,
    ) -> Any: ...
    def branches(self, ledger: str) -> list[dict[str, Any]]: ...
    def create_branch(self, ledger: str, name: str, at: tuple[str, Any] | None = None) -> str: ...
    def drop_branch(self, ledger: str) -> None: ...
    def merge(self, target: str, source: str, strategy: str) -> dict[str, Any]: ...
    def rebase(self, ledger: str, strategy: str) -> dict[str, Any]: ...
    def revert(self, ledger: str, commits: list[int | str], strategy: str) -> dict[str, Any]: ...
    def merge_preview(self, target: str, source: str, options: dict[str, Any]) -> dict[str, Any]: ...
    def revert_preview(self, ledger: str, commits: list[int | str], options: dict[str, Any]) -> dict[str, Any]: ...

class Snapshot:
    @property
    def ledger(self) -> str: ...
    @property
    def t(self) -> int: ...
    def query_sparql(
        self, sparql: str, controls: Controls | None = None, params: dict[str, Any] | None = None
    ) -> Any: ...
    def query_jsonld(self, query: Any, controls: Controls | None = None) -> Any: ...
    def stream(
        self, query: Any, controls: Controls | None = None, params: dict[str, Any] | None = None
    ) -> RowStream: ...
    def explain(self, query: Any, params: dict[str, Any] | None = None) -> dict[str, Any]: ...
    def cypher_query(
        self, cypher: str, params: dict[str, Any] | None = None, controls: Controls | None = None
    ) -> tuple[list[str], list[tuple[Any, ...]]]: ...
    def explain_cypher(self, cypher: str, params: dict[str, Any] | None = None) -> dict[str, Any]: ...

class RowStream:
    @property
    def columns(self) -> list[str] | None: ...
    def next_batch(self, max: int) -> list[tuple[Any, ...]] | None: ...
    def close(self) -> None: ...

class Transaction:
    @property
    def ledger(self) -> str: ...
    @property
    def is_open(self) -> bool: ...
    def stage(self, op: str, kind: str, payload: Any, params: dict[str, Any] | None = None) -> None: ...
    def stage_cypher(
        self, query: str, params: dict[str, Any] | None = None
    ) -> tuple[list[str], list[tuple[Any, ...]]] | None: ...
    def snapshot(self) -> Snapshot: ...
    def commit(self, message: str | None = None) -> dict[str, Any]: ...
    def rollback(self) -> None: ...

def sparql_form(sparql: str) -> str | None: ...
def set_log_level(level: int) -> None: ...

class Canceller:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
