#!/bin/bash

echo "GraalVM Installation Instructions for Java 11"
echo "============================================="
echo ""
echo "Option 1: Using Homebrew (macOS):"
echo "  brew install --cask graalvm-ce-java11"
echo "  export GRAALVM_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java11/Contents/Home"
echo "  export PATH=\$GRAALVM_HOME/bin:\$PATH"
echo "  gu install native-image"
echo ""
echo "Option 2: Using SDKMAN:"
echo "  curl -s https://get.sdkman.io | bash"
echo "  sdk install java 22.3.5-graalce"
echo "  sdk use java 22.3.5-graalce"
echo "  gu install native-image"
echo ""
echo "Option 3: Manual download:"
echo "  Download from: https://github.com/graalvm/graalvm-ce-builds/releases"
echo "  Extract and set GRAALVM_HOME"
echo "  Run: \$GRAALVM_HOME/bin/gu install native-image"
echo ""
echo "After installation, verify with:"
echo "  java -version  # Should show GraalVM"
echo "  native-image --version"