;; This file is auto-generated by target-bundle-libs. DO NOT EDIT!

{:npm-deps {"bufferutil" "^4.0.7", "utf-8-validate" "^6.0.3", "axios" "^1.5.1", "jsonld" "^8.3.1", "@cljs-oss/module-deps" "^1.1.1", "seedrandom" "^3.0.5", "source-map-support" "^0.5.21", "js-sha3" "^0.9.2", "scrypt-js" "^3.0.1", "ws" "^8.14.2", "form-data" "^4.0.0", "@fluree/sjcl" "^1.0.8-3"}}