;; This file is auto-generated by target-bundle-libs. DO NOT EDIT!

{:npm-deps {"bufferutil" "4.0.6", "utf-8-validate" "5.0.9", "axios" "0.27.2", "@cljs-oss/module-deps" "1.1.1", "seedrandom" "^3.0.5", "source-map-support" "0.5.21", "js-sha3" "0.8.0", "scrypt-js" "3.0.1", "ws" "8.8.0", "form-data" "4.0.0", "@fluree/sjcl" "1.0.8-3"}}