;; This file is auto-generated by target-bundle-libs. DO NOT EDIT!

{:npm-deps {"bufferutil" "^4.0.3", "utf-8-validate" "^5.0.5", "axios" "^0.21.4", "@cljs-oss/module-deps" "^1.1.1", "source-map-support" "^0.5.19", "js-sha3" "^0.8.0", "scrypt-js" "^3.0.1", "ws" "^8.2.1", "@fluree/sjcl" "^1.0.8-3"}}