;; This file is auto-generated by target-bundle-libs. DO NOT EDIT!

{:npm-deps {"@cljs-oss/module-deps" "^1.1.1", "@fluree/sjcl" "^1.0.8-3", "axios" "^0.21.1", "js-sha3" "^0.8.0", "scrypt-js" "^2.0.4", "source-map-support" "^0.5.19", "ws" "7.4.6"}}